<?xml version="1.0"?>
<package format="3">
  <name>fixposition_sensor_pkg</name>
  <version>0.0.0</version>
  <description>Sensor plugin for Fixposition with custom message types.</description>
  <maintainer email="manuel.sanchez.m@uma.es">roverj8</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Standard dependencies -->
  <depend>gazebo_dev</depend>
  <depend>gazebo_ros</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>sensor_msgs</depend>
  <depend>gazebo_plugins</depend>

  <!-- Custom message package -->
  <build_depend>fixposition_msgs</build_depend>
  <exec_depend>fixposition_msgs</exec_depend>

  <!-- Rosidl default generators for messages -->
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Testing dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

